use super::*;

use std::{
    collections::HashMap,
    env,
    ffi::OsStr,
    fs::OpenOptions,
    io::{self, Write},
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::{anyhow, bail, Context, Result};
use dirs::home_dir;
use std::sync::LazyLock;

pub static SHELL: LazyLock<Shell> = LazyLock::new(detect_shell);

pub struct Shell {
    pub name: String,
    pub cmd: String,
    pub arg: String,
}

impl Shell {
    pub fn new(name: &str, cmd: &str, arg: &str) -> Self {
        Self {
            name: name.to_string(),
            cmd: cmd.to_string(),
            arg: arg.to_string(),
        }
    }
}

pub fn detect_shell() -> Shell {
    let cmd = env::var(get_env_name("shell")).ok().or_else(|| {
        if cfg!(windows) {
            if let Ok(ps_module_path) = env::var("PSModulePath") {
                let ps_module_path = ps_module_path.to_lowercase();
                if ps_module_path.starts_with(r"c:\users") {
                    if ps_module_path.contains(r"\powershell\7\") {
                        return Some("pwsh.exe".to_string());
                    } else {
                        return Some("powershell.exe".to_string());
                    }
                }
            }
            None
        } else {
            env::var("SHELL").ok()
        }
    });
    let name = cmd
        .as_ref()
        .and_then(|v| Path::new(v).file_stem().and_then(|v| v.to_str()))
        .map(|v| {
            if v == "nu" {
                "nushell".into()
            } else {
                v.to_lowercase()
            }
        });
    let (cmd, name) = match (cmd.as_deref(), name.as_deref()) {
        (Some(cmd), Some(name)) => (cmd, name),
        _ => {
            if cfg!(windows) {
                ("cmd.exe", "cmd")
            } else {
                ("/bin/sh", "sh")
            }
        }
    };
    let shell_arg = match name {
        "powershel" => "-Command",
        "cmd" => "/C",
        _ => "-c",
    };
    Shell::new(name, cmd, shell_arg)
}

pub fn run_command<T: AsRef<OsStr>>(
    cmd: &str,
    args: &[T],
    envs: Option<HashMap<String, String>>,
) -> Result<i32> {
    let status = Command::new(cmd)
        .args(args.iter())
        .envs(envs.unwrap_or_default())
        .status()?;
    Ok(status.code().unwrap_or_default())
}

pub fn run_command_with_output<T: AsRef<OsStr>>(
    cmd: &str,
    args: &[T],
    envs: Option<HashMap<String, String>>,
) -> Result<(bool, String, String)> {
    let output = Command::new(cmd)
        .args(args.iter())
        .envs(envs.unwrap_or_default())
        .output()?;
    let status = output.status;
    let stdout = std::str::from_utf8(&output.stdout).context("Invalid UTF-8 in stdout")?;
    let stderr = std::str::from_utf8(&output.stderr).context("Invalid UTF-8 in stderr")?;
    Ok((status.success(), stdout.to_string(), stderr.to_string()))
}

pub fn run_loader_command(path: &str, extension: &str, loader_command: &str) -> Result<String> {
    let cmd_args = shell_words::split(loader_command)
        .with_context(|| anyhow!("Invalid document loader '{extension}': `{loader_command}`"))?;
    let outpath = temp_file("-output-", "").display().to_string();
    let safe_path = sanitize_loader_path(path);
    let (cmd_args, has_outpath) = expand_loader_placeholders(cmd_args, &safe_path, &outpath);
    let use_stdout = !has_outpath;
    let cmd_eval = shell_words::join(&cmd_args);
    debug!("run `{cmd_eval}`");
    let (cmd, args) = cmd_args
        .split_first()
        .ok_or_else(|| anyhow!("Document loader '{extension}' is empty"))?;
    if use_stdout {
        let (success, stdout, stderr) =
            run_command_with_output(cmd, args, None).with_context(|| {
                format!("Unable to run `{cmd_eval}`, Perhaps '{cmd}' is not installed?")
            })?;
        if !success {
            let err = if !stderr.is_empty() {
                stderr
            } else {
                format!("The command `{cmd_eval}` exited with non-zero.")
            };
            bail!("{err}")
        }
        Ok(stdout)
    } else {
        let status = run_command(cmd, args, None).with_context(|| {
            format!("Unable to run `{cmd_eval}`, Perhaps '{cmd}' is not installed?")
        })?;
        if status != 0 {
            bail!("The command `{cmd_eval}` exited with non-zero.")
        }
        let contents = std::fs::read_to_string(&outpath)
            .context("Failed to read file generated by the loader")?;
        Ok(contents)
    }
}

fn sanitize_loader_path(path: &str) -> String {
    if path.starts_with('-') && !Path::new(path).is_absolute() {
        format!("./{path}")
    } else {
        path.to_string()
    }
}

fn expand_loader_placeholders(args: Vec<String>, path: &str, outpath: &str) -> (Vec<String>, bool) {
    let mut has_outpath = false;
    let args = args
        .into_iter()
        .map(|arg| {
            let (arg, arg_has_outpath) = replace_loader_placeholders(&arg, path, outpath);
            has_outpath |= arg_has_outpath;
            arg
        })
        .collect();
    (args, has_outpath)
}

fn replace_loader_placeholders(template: &str, path: &str, outpath: &str) -> (String, bool) {
    let mut result = String::with_capacity(template.len());
    let mut chars = template.chars().peekable();
    let mut has_outpath = false;

    while let Some(ch) = chars.next() {
        if ch == '$' {
            match chars.peek() {
                Some('1') => {
                    chars.next();
                    result.push_str(path);
                    continue;
                }
                Some('2') => {
                    chars.next();
                    result.push_str(outpath);
                    has_outpath = true;
                    continue;
                }
                _ => {}
            }
        }
        result.push(ch);
    }

    (result, has_outpath)
}

pub fn edit_file(editor: &str, path: &Path) -> Result<()> {
    let mut command = editor_command(editor)?;
    let mut child = command
        .arg(path)
        .spawn()
        .with_context(|| format!("Unable to start editor `{editor}` for '{}'", path.display()))?;
    let status = child.wait().with_context(|| {
        format!(
            "Unable to wait for editor `{editor}` while editing '{}'",
            path.display()
        )
    })?;
    if !status.success() {
        bail!(
            "Editor `{editor}` exited with {status} while editing '{}'",
            path.display()
        )
    }
    Ok(())
}

pub fn editor_command(editor: &str) -> Result<Command> {
    let args = parse_editor_command(editor)?;
    let (program, args) = args
        .split_first()
        .ok_or_else(|| anyhow!("Editor command is empty"))?;
    let mut command = Command::new(program);
    command.args(args);
    Ok(command)
}

pub fn resolve_editor_command<F>(
    configured: Option<&str>,
    visual: Option<&str>,
    editor: Option<&str>,
    default: &str,
    executable_exists: F,
) -> Result<String>
where
    F: FnOnce(&str) -> bool,
{
    let editor = [configured, visual, editor]
        .into_iter()
        .flatten()
        .find(|value| !value.trim().is_empty())
        .unwrap_or(default)
        .to_string();
    let args = parse_editor_command(&editor)?;
    let program = args
        .first()
        .ok_or_else(|| anyhow!("Editor command is empty"))?;
    if !executable_exists(program) {
        bail!("Editor executable '{program}' from `{editor}` was not found")
    }
    Ok(editor)
}

fn parse_editor_command(editor: &str) -> Result<Vec<String>> {
    // Use one grammar on every platform and invoke the program directly, without a shell. Quoting
    // is therefore deterministic and shell operators are ordinary arguments.
    shell_words::split(editor).with_context(|| {
        format!(
            "Invalid editor command `{editor}`; use POSIX shell-word quoting, including on Windows"
        )
    })
}

pub fn append_to_shell_history(shell: &str, command: &str, exit_code: i32) -> io::Result<()> {
    if let Some(history_file) = get_history_file(shell) {
        let command = command.replace('\n', " ");
        let now = now_timestamp();
        let history_txt = if shell == "fish" {
            format!("- cmd: {command}\n  when: {now}")
        } else if shell == "zsh" {
            format!(": {now}:{exit_code};{command}",)
        } else {
            command
        };
        let mut file = OpenOptions::new()
            .create(true)
            .append(true)
            .open(&history_file)?;
        writeln!(file, "{history_txt}")?;
    }
    Ok(())
}

fn get_history_file(shell: &str) -> Option<PathBuf> {
    match shell {
        "bash" | "sh" => env::var("HISTFILE")
            .ok()
            .map(PathBuf::from)
            .or(Some(home_dir()?.join(".bash_history"))),
        "zsh" => env::var("HISTFILE")
            .ok()
            .map(PathBuf::from)
            .or(Some(home_dir()?.join(".zsh_history"))),
        "nushell" => Some(dirs::config_dir()?.join("nushell").join("history.txt")),
        "fish" => Some(
            home_dir()?
                .join(".local")
                .join("share")
                .join("fish")
                .join("fish_history"),
        ),
        "powershell" | "pwsh" => {
            #[cfg(not(windows))]
            {
                Some(
                    home_dir()?
                        .join(".local")
                        .join("share")
                        .join("powershell")
                        .join("PSReadLine")
                        .join("ConsoleHost_history.txt"),
                )
            }
            #[cfg(windows)]
            {
                Some(
                    dirs::data_dir()?
                        .join("Microsoft")
                        .join("Windows")
                        .join("PowerShell")
                        .join("PSReadLine")
                        .join("ConsoleHost_history.txt"),
                )
            }
        }
        "ksh" => Some(home_dir()?.join(".ksh_history")),
        "tcsh" => Some(home_dir()?.join(".history")),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(unix)]
    #[test]
    fn editor_command_accepts_arguments() {
        edit_file("/bin/sh -c true", Path::new("/dev/null")).unwrap();
    }

    #[test]
    fn editor_resolution_has_deterministic_priority() {
        let found = |program: &str| program == "configured";
        let editor = resolve_editor_command(
            Some("configured --wait"),
            Some("visual"),
            Some("editor"),
            "default",
            found,
        )
        .unwrap();
        assert_eq!(editor, "configured --wait");

        let editor = resolve_editor_command(
            Some("  "),
            Some("visual --wait"),
            Some("editor"),
            "default",
            |program| program == "visual",
        )
        .unwrap();
        assert_eq!(editor, "visual --wait");

        let editor = resolve_editor_command(None, None, Some("editor"), "default", |program| {
            program == "editor"
        })
        .unwrap();
        assert_eq!(editor, "editor");

        let editor =
            resolve_editor_command(None, None, None, "default", |program| program == "default")
                .unwrap();
        assert_eq!(editor, "default");
    }

    #[test]
    fn editor_parser_supports_quoted_paths_on_all_platforms() {
        let args = parse_editor_command(r#""C:\Program Files\Helix\hx.exe" --wait"#).unwrap();
        assert_eq!(args, [r"C:\Program Files\Helix\hx.exe", "--wait"]);
    }

    #[test]
    fn editor_parser_rejects_malformed_quotes() {
        let error = parse_editor_command("helix '").unwrap_err();
        assert!(error.to_string().contains("Invalid editor command"));
        assert!(error.to_string().contains("POSIX shell-word quoting"));
    }

    #[test]
    fn editor_resolution_reports_missing_executable() {
        let error =
            resolve_editor_command(None, Some("missing-editor --wait"), None, "default", |_| {
                false
            })
            .unwrap_err();
        assert_eq!(
            error.to_string(),
            "Editor executable 'missing-editor' from `missing-editor --wait` was not found"
        );
    }

    #[test]
    fn loader_path_prevents_leading_dash_options() {
        assert_eq!(sanitize_loader_path("-v"), "./-v");
        assert_eq!(sanitize_loader_path("--output=file"), "./--output=file");
        assert_eq!(sanitize_loader_path("file.txt"), "file.txt");
        assert_eq!(sanitize_loader_path("/tmp/-v"), "/tmp/-v");
        assert_eq!(
            sanitize_loader_path(r"C:\Users\user\-v.txt"),
            r"C:\Users\user\-v.txt"
        );
    }

    #[test]
    fn loader_placeholders_are_expanded_once() {
        let path = "file $2 with 'quotes' and \"double quotes\"\nnext line.md";
        let outpath = "/tmp/result $1.txt";
        let (value, has_outpath) =
            replace_loader_placeholders("input=$1 repeated=$1", path, outpath);

        assert_eq!(value, format!("input={path} repeated={path}"));
        assert!(!has_outpath);
        assert!(value.contains("$2"));

        let (value, has_outpath) =
            replace_loader_placeholders("input=$1 output=$2 output-again=$2", path, outpath);
        assert_eq!(
            value,
            format!("input={path} output={outpath} output-again={outpath}")
        );
        assert!(has_outpath);
        assert!(value.contains("$1.txt"));
    }

    #[test]
    fn loader_filename_remains_one_argument() {
        let path = sanitize_loader_path("-file with spaces, 'quotes', and\nnewline $2.md");
        let args = shell_words::split("loader --input '$1' tail").unwrap();
        let (args, has_outpath) = expand_loader_placeholders(args, &path, "/tmp/output");

        assert_eq!(args, vec!["loader", "--input", &path, "tail"]);
        assert!(!has_outpath);
    }

    #[test]
    fn loader_output_placeholder_detection_ignores_inserted_text() {
        let windows_path = r"C:\Users\user\file $2.md";
        let args = vec!["loader".to_string(), "$1".to_string()];
        let (args, has_outpath) = expand_loader_placeholders(args, windows_path, "/tmp/output");

        assert_eq!(args, vec!["loader", windows_path]);
        assert!(!has_outpath);

        let args = vec!["loader".to_string(), "$1".to_string(), "$2".to_string()];
        let (args, has_outpath) = expand_loader_placeholders(args, windows_path, "/tmp/output");
        assert_eq!(args, vec!["loader", windows_path, "/tmp/output"]);
        assert!(has_outpath);
    }
}
